services:
  database:
    restart: always
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tensorDB
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
